language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  allow_failures:
    - stage: build
      os: osx
      env:
        - azure-osx

  include:
    # This builder only tests code linters on latest version of Go
    - stage: lint
      os: linux
      dist: bionic
      go: 1.21.4
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint

    - stage: build
      os: linux
      arch: amd64
      dist: bionic
      go: 1.21.4
      env:
        - GO111MODULE=on
      script:
        - travis_wait 120 go run build/ci.go test -dlgo $TEST_PACKAGES
